mighty_django/main/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name="main_index"),
]

mighty_django/mighty_django/urls.py
from django.contrib import admin
from django.urls import path, include
from main import urls as main_urls
from posts import urls as posts_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include(main_urls)),
    path('posts/', include(posts_urls)),
]

mighty_django/posts/urls.py
from django.urls import path
from .views import *

app_name = "posts"
urlpatterns = [
    path('new/', new , name="new"),
    path('create/', create, name="create"),
    # path('show/', show, name="show"),
    path('show/<int:post_id>/', show, name="show"),
    path('edit/<int:post_id>/', edit, name="edit"),
    path('update/<int:post_id>/', update, name="update"),
    path('delete/<int:post_id>/', delete, name="delete"),
]

mighty_django/main/models.py
from django.db import models

# Create your models here.

mighty_django/posts/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Post(models.Model):
    class Meta:
        ordering = ['-created_at']

    title = models.CharField(max_length= 200)
    content = models.TextField()
    view_content = models.IntegerField(default= 0)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

    def __str__(self):
        return self.title



    def get_absolute_url(self):
        return reverse('posts:show', args=[self.id])

mighty_django/posts/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content']
        labels = {
            'title': '제목',
            'content': '내용'
        }
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs ={'class': 'form-control'})
        }

mighty_django/main/views.py
from django.shortcuts import render
from . import urls
from posts.models import Post
# Create your views here.

def index(request):
    context = {
        'posts': Post.objects.all()
    }
    return render(request, 'main/index.html', context)

mighty_django/posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Post
from .forms import PostForm
from django.views.decorators.http import require_POST
# Create your views here.

def new(request):
    form = PostForm()
    return render(request, 'posts/new.html', {'form': form})

@require_POST
def create(request):
    # title = request.POST.get('title')
    # content = request.POST.get('content')
    # Post.objects.create(title= title, content= content)
    # Post.save()
    form = PostForm(request.POST)
    if form.is_valid():
        form.save()
    # return redirect('main_index')
    return redirect(form.instance)

def show(request, post_id):
    # post_id = request.GET.get('post_id')
    # post = Post.objects.get(id=post_id)
    post = get_object_or_404(Post, pk=post_id)
    context = {
        'post': post
    }
    return render(request, 'posts/show.html', context)

def edit(request, post_id):
    post = Post.objects.get(id=post_id)
    context = {
        'post': post,
        'form': PostForm(instance=post)
    }
    return render(request, 'posts/edit.html', context)

def update(request, post_id):
    post = Post.objects.get(id=post_id)
    form = PostForm(request.POST, instance = post)
    if form.is_valid():
        form.save()
    return redirect(post)

def delete(request, post_id):
    post = Post.objects.get(id=post_id)
    post.delete()
    return redirect('main_index')

mighty_django/main/templates/main/index.html
{% extends 'base.html'%}
{% load static %}
{% block content %}
<div class="container">
  {% for post in posts %}
    {{post.title}} <br>
    {{post.content}} <br>
    <a href="{{ post.get_absolute_url }}">이동</a>
    <br><br>
  {% endfor %}
</div>
{% endblock %}

mighty_django/posts/templates/posts/_form.html
{% csrf_token%}
{{form.as_p}}
<input type="submit" value="{{btn_value}}" class="btn btn-warning">

mighty_django/posts/templates/posts/edit.html
{% extends 'base.html'%}
{% block content%}
<h1>글 수정</h1>
<form action="{% url 'posts:update' post.id %}" method="POST">
  {% include 'posts/_form.html' with form=form btn_value="글수정"%}
</form>
{% endblock %}

mighty_django/posts/templates/posts/new.html
{% extends 'base.html' %}

{% block content %}

<form action="{% url 'posts:create' %}" method="POST">
  {% csrf_token %}
  {{form}}
  <button class="btn btn-primary">제출</button>
</form>


{% endblock %}

mighty_django/posts/templates/posts/show.html
{% extends 'base.html' %}
{% block content%}
  상세피이지

제목 : {{post.title}} <br>

내용 : {{post.content}} <br>

<a href="{% url 'posts:edit' post.id %}" class="btn btn-primary">수정하기</a>
<a href="#" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">삭제</a>



<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">정말 삭제?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <form action="{% url 'posts:delete' post.pk %}" method="POST">
          {% csrf_token %}
          <input type="submit" value="삭제">
        </form>

      </div>
    </div>
  </div>
</div>
{% endblock %}